# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc/file_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/grpc/file_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pp/grpc/file_service.proto\"2\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"!\n\x0eUploadResponse\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\"\"\n\x0f\x44ownloadRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\"5\n\x10\x44ownloadResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x32q\n\x0b\x46ileService\x12-\n\nUploadFile\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\x12\x33\n\x0c\x44ownloadFile\x12\x10.DownloadRequest\x1a\x11.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc.file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=31
  _globals['_UPLOADREQUEST']._serialized_end=81
  _globals['_UPLOADRESPONSE']._serialized_start=83
  _globals['_UPLOADRESPONSE']._serialized_end=116
  _globals['_DOWNLOADREQUEST']._serialized_start=118
  _globals['_DOWNLOADREQUEST']._serialized_end=152
  _globals['_DOWNLOADRESPONSE']._serialized_start=154
  _globals['_DOWNLOADRESPONSE']._serialized_end=207
  _globals['_FILESERVICE']._serialized_start=209
  _globals['_FILESERVICE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
